import { forwardRef } from 'react';
import { createLucideIcon, type LucideProps } from 'lucide-react';

// Keep technical controls and their established semantics. Explicit exports below
// replace only icons covered by the approved Altitud collection.
export * from 'lucide-react';

const Glyph_fuerza = createLucideIcon('Altitud-fuerza', [["rect",{"x":"4","y":"6","width":"3","height":"12","rx":"1","key":"0"}],["rect",{"x":"17","y":"6","width":"3","height":"12","rx":"1","key":"1"}],["path",{"d":"M7 12h10M2 9v6M22 9v6","key":"2"}]]);
const Brand_fuerza = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_fuerza ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_fuerza.displayName = 'Altitud-fuerza';
const Glyph_running = createLucideIcon('Altitud-running', [["circle",{"cx":"15","cy":"4","r":"1.7","key":"0"}],["path",{"d":"m4 10 4-2 4 2 3 4 5 1M12 10l2-3 3 3h3M11 13l-2 4-5 3M11 13l4 5-1 4","key":"1"}]]);
const Brand_running = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_running ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_running.displayName = 'Altitud-running';
const Glyph_intervalos = createLucideIcon('Altitud-intervalos', [["circle",{"cx":"12","cy":"14","r":"7.5","key":"0"}],["path",{"d":"M10 2h4M12 2v4M18 7l2-2M12 10v4l3 2","key":"1"}]]);
const Brand_intervalos = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_intervalos ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_intervalos.displayName = 'Altitud-intervalos';
const Glyph_rendimiento = createLucideIcon('Altitud-rendimiento', [["path",{"d":"M4 20V5M4 20h16M8 16l4-5 3 2 5-8M16 5h4v4","key":"0"}]]);
const Brand_rendimiento = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_rendimiento ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_rendimiento.displayName = 'Altitud-rendimiento';
const Glyph_ruta = createLucideIcon('Altitud-ruta', [["circle",{"cx":"5","cy":"19","r":"2","key":"0"}],["circle",{"cx":"19","cy":"5","r":"2","key":"1"}],["path",{"d":"M7 19h8a4 4 0 0 0 0-8H9a4 4 0 0 1 0-8h5M16 3l-2 2","key":"2"}]]);
const Brand_ruta = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_ruta ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_ruta.displayName = 'Altitud-ruta';
const Glyph_perfil = createLucideIcon('Altitud-perfil', [["circle",{"cx":"12","cy":"7","r":"3.5","key":"0"}],["path",{"d":"M4 21v-2a8 8 0 0 1 16 0v2","key":"1"}]]);
const Brand_perfil = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_perfil ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_perfil.displayName = 'Altitud-perfil';
const Glyph_comunidad = createLucideIcon('Altitud-comunidad', [["circle",{"cx":"12","cy":"7","r":"3","key":"0"}],["path",{"d":"M6 21v-2a6 6 0 0 1 12 0v2M4 5a3 3 0 0 0 0 6M20 5a3 3 0 0 1 0 6M2 19v-2a5 5 0 0 1 3-4M22 19v-2a5 5 0 0 0-3-4","key":"1"}]]);
const Brand_comunidad = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_comunidad ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_comunidad.displayName = 'Altitud-comunidad';
const Glyph_logro = createLucideIcon('Altitud-logro', [["circle",{"cx":"12","cy":"9","r":"6","key":"0"}],["path",{"d":"m8 14-2 8 6-3 6 3-2-8M9 9l2 2 4-4","key":"1"}]]);
const Brand_logro = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_logro ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_logro.displayName = 'Altitud-logro';
const Glyph_objetivo = createLucideIcon('Altitud-objetivo', [["circle",{"cx":"12","cy":"12","r":"9","key":"0"}],["circle",{"cx":"12","cy":"12","r":"5","key":"1"}],["circle",{"cx":"12","cy":"12","r":"1","key":"2"}]]);
const Brand_objetivo = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_objetivo ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_objetivo.displayName = 'Altitud-objetivo';
const Glyph_racha = createLucideIcon('Altitud-racha', [["path",{"d":"M13 2c1 5-3 6-1 9 2-1 3-3 3-5 4 4 6 7 5 11a8 8 0 0 1-15 0c-1-4 2-7 5-10-1 3-1 4 0 5 2-3 0-5 3-10Z","key":"0"}]]);
const Brand_racha = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_racha ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_racha.displayName = 'Altitud-racha';
const Glyph_bienestar = createLucideIcon('Altitud-bienestar', [["path",{"d":"M12 21S3 16 3 9a5 5 0 0 1 9-3 5 5 0 0 1 9 3c0 7-9 12-9 12Z","key":"0"}],["path",{"d":"M5 12h4l2-4 3 8 2-4h3","key":"1"}]]);
const Brand_bienestar = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_bienestar ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_bienestar.displayName = 'Altitud-bienestar';
const Glyph_ubicacion = createLucideIcon('Altitud-ubicacion', [["path",{"d":"M19 9c0 5-7 13-7 13S5 14 5 9a7 7 0 0 1 14 0Z","key":"0"}],["circle",{"cx":"12","cy":"9","r":"2.5","key":"1"}]]);
const Brand_ubicacion = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_ubicacion ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_ubicacion.displayName = 'Altitud-ubicacion';
const Glyph_calendario = createLucideIcon('Altitud-calendario', [["rect",{"x":"3","y":"5","width":"18","height":"16","rx":"2","key":"0"}],["path",{"d":"M7 2v6M17 2v6M3 10h18M7 14h2M15 14h2M7 18h2","key":"1"}]]);
const Brand_calendario = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_calendario ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_calendario.displayName = 'Altitud-calendario';
const Glyph_horario = createLucideIcon('Altitud-horario', [["circle",{"cx":"12","cy":"12","r":"9","key":"0"}],["path",{"d":"M12 6v6l4 2","key":"1"}]]);
const Brand_horario = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_horario ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_horario.displayName = 'Altitud-horario';
const Glyph_reservar = createLucideIcon('Altitud-reservar', [["rect",{"x":"3","y":"5","width":"18","height":"16","rx":"2","key":"0"}],["path",{"d":"M7 2v6M17 2v6M3 10h18M12 13v5M9.5 15.5h5","key":"1"}]]);
const Brand_reservar = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_reservar ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_reservar.displayName = 'Altitud-reservar';
const Glyph_confirmado = createLucideIcon('Altitud-confirmado', [["circle",{"cx":"12","cy":"12","r":"9","key":"0"}],["path",{"d":"m7.5 12 3 3 6-6","key":"1"}]]);
const Brand_confirmado = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_confirmado ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_confirmado.displayName = 'Altitud-confirmado';
const Glyph_cancelar = createLucideIcon('Altitud-cancelar', [["circle",{"cx":"12","cy":"12","r":"9","key":"0"}],["path",{"d":"m8.5 8.5 7 7M15.5 8.5l-7 7","key":"1"}]]);
const Brand_cancelar = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_cancelar ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_cancelar.displayName = 'Altitud-cancelar';
const Glyph_espera = createLucideIcon('Altitud-espera', [["path",{"d":"M4 4h16M4 20h16M6 4c0 4 1 6 6 8-5 2-6 4-6 8M18 4c0 4-1 6-6 8 5 2 6 4 6 8M9 7h6M9 18h6","key":"0"}]]);
const Brand_espera = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_espera ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_espera.displayName = 'Altitud-espera';
const Glyph_checkin = createLucideIcon('Altitud-checkin', [["path",{"d":"M9 4h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H9M2 12h12M10 8l4 4-4 4","key":"0"}]]);
const Brand_checkin = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_checkin ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_checkin.displayName = 'Altitud-checkin';
const Glyph_qr = createLucideIcon('Altitud-qr', [["rect",{"x":"3","y":"3","width":"6","height":"6","rx":"0.7","key":"0"}],["rect",{"x":"15","y":"3","width":"6","height":"6","rx":"0.7","key":"1"}],["rect",{"x":"3","y":"15","width":"6","height":"6","rx":"0.7","key":"2"}],["path",{"d":"M15 15h3v3h3v3h-6v-3M21 14v1","key":"3"}]]);
const Brand_qr = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_qr ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_qr.displayName = 'Altitud-qr';
const Glyph_membresia = createLucideIcon('Altitud-membresia', [["rect",{"x":"2","y":"5","width":"20","height":"14","rx":"2","key":"0"}],["circle",{"cx":"7","cy":"11","r":"2","key":"1"}],["path",{"d":"M4 16a3 3 0 0 1 6 0M14 10h5M14 14h3","key":"2"}]]);
const Brand_membresia = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_membresia ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_membresia.displayName = 'Altitud-membresia';
const Glyph_ilimitado = createLucideIcon('Altitud-ilimitado', [["path",{"d":"M12 12c-2.5-3.5-3.5-4.5-5.5-4.5a4.5 4.5 0 0 0 0 9c2 0 3-1 5.5-4.5Zm0 0c2.5-3.5 3.5-4.5 5.5-4.5a4.5 4.5 0 0 1 0 9c-2 0-3-1-5.5-4.5Z","key":"0"}]]);
const Brand_ilimitado = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_ilimitado ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_ilimitado.displayName = 'Altitud-ilimitado';
const Glyph_pago = createLucideIcon('Altitud-pago', [["rect",{"x":"2","y":"5","width":"20","height":"14","rx":"2","key":"0"}],["path",{"d":"M2 10h20M6 15h4","key":"1"}]]);
const Brand_pago = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_pago ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_pago.displayName = 'Altitud-pago';
const Glyph_transferencia = createLucideIcon('Altitud-transferencia', [["path",{"d":"M3 7h18M17 3l4 4-4 4M21 17H3M7 13l-4 4 4 4","key":"0"}]]);
const Brand_transferencia = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_transferencia ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_transferencia.displayName = 'Altitud-transferencia';
const Glyph_comprobante = createLucideIcon('Altitud-comprobante', [["path",{"d":"M5 2h10l4 4v16l-3-2-4 2-4-2-3 2ZM15 2v5h4M8 11h8M8 15h5","key":"0"}]]);
const Brand_comprobante = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_comprobante ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_comprobante.displayName = 'Altitud-comprobante';
const Glyph_notificacion = createLucideIcon('Altitud-notificacion', [["path",{"d":"M5 10a7 7 0 0 1 14 0v5l2 3H3l2-3ZM9 21h6M12 1v2","key":"0"}]]);
const Brand_notificacion = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_notificacion ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_notificacion.displayName = 'Altitud-notificacion';
const Glyph_ajustes = createLucideIcon('Altitud-ajustes', [["path",{"d":"M5 3v5M5 12v9M12 3v10M12 17v4M19 3v2M19 9v12","key":"0"}],["circle",{"cx":"5","cy":"10","r":"2","key":"1"}],["circle",{"cx":"12","cy":"15","r":"2","key":"2"}],["circle",{"cx":"19","cy":"7","r":"2","key":"3"}]]);
const Brand_ajustes = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_ajustes ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_ajustes.displayName = 'Altitud-ajustes';
const Glyph_ayuda = createLucideIcon('Altitud-ayuda', [["circle",{"cx":"12","cy":"12","r":"9","key":"0"}],["path",{"d":"M9 9a3 3 0 1 1 5 2c-1 1-2 1-2 3M12 17h.01","key":"1"}]]);
const Brand_ayuda = forwardRef<SVGSVGElement, LucideProps>((props, ref) => <Glyph_ayuda ref={ref} strokeWidth={1.65} aria-hidden={props['aria-label'] || props['aria-labelledby'] ? undefined : true} {...props} />);
Brand_ayuda.displayName = 'Altitud-ayuda';
export const Dumbbell = Brand_fuerza;
export const Footprints = Brand_running;
export const Timer = Brand_intervalos;
export const TrendingUp = Brand_rendimiento;
export const Route = Brand_ruta;
export const User = Brand_perfil;
export const UserRound = Brand_perfil;
export const Users = Brand_comunidad;
export const UsersRound = Brand_comunidad;
export const Award = Brand_logro;
export const Medal = Brand_logro;
export const Trophy = Brand_logro;
export const Target = Brand_objetivo;
export const Flame = Brand_racha;
export const Heart = Brand_bienestar;
export const HeartPulse = Brand_bienestar;
export const MapPin = Brand_ubicacion;
export const Calendar = Brand_calendario;
export const CalendarDays = Brand_calendario;
export const Clock = Brand_horario;
export const Clock3 = Brand_horario;
export const Clock4 = Brand_horario;
export const CalendarPlus = Brand_reservar;
export const CheckCircle = Brand_confirmado;
export const CheckCircle2 = Brand_confirmado;
export const CircleCheck = Brand_confirmado;
export const XCircle = Brand_cancelar;
export const CircleX = Brand_cancelar;
export const Hourglass = Brand_espera;
export const LogIn = Brand_checkin;
export const QrCode = Brand_qr;
export const IdCard = Brand_membresia;
export const ContactRound = Brand_membresia;
export const Infinity = Brand_ilimitado;
export const CreditCard = Brand_pago;
export const ArrowLeftRight = Brand_transferencia;
export const ArrowRightLeft = Brand_transferencia;
export const Receipt = Brand_comprobante;
export const ReceiptText = Brand_comprobante;
export const FileCheck = Brand_comprobante;
export const Bell = Brand_notificacion;
export const BellRing = Brand_notificacion;
export const Settings = Brand_ajustes;
export const Settings2 = Brand_ajustes;
export const SlidersHorizontal = Brand_ajustes;
export const HelpCircle = Brand_ayuda;
export const CircleHelp = Brand_ayuda;
