import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { AuthGuard } from '@/components/layout/AuthGuard';
import { useAuthStore } from '@/stores/authStore';
import api, { getErrorMessage } from '@/lib/api';
import { Link } from 'react-router-dom';

type Session={id:string;date:string;start_time:string;end_time:string;class_type_name:string;current_bookings:number;max_capacity:number};
type Attendee={booking_id:string;display_name:string;status:string;alert_flag?:boolean;alert_message?:string;instructor_notes?:string};
function CoachContent(){
 const {user,logout}=useAuthStore(); const id=user?.instructor_id;const cache=useQueryClient();const [selected,setSelected]=useState<Session|null>(null);const [error,setError]=useState('');
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Mexico_City',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const end=new Date(`${today}T12:00:00Z`);end.setUTCDate(end.getUTCDate()+7);
 const sessions=useQuery<Session[]>({queryKey:['coach-classes',id,today],queryFn:async()=> (await api.get(`/instructors/${id}/classes?from=${today}&to=${end.toISOString().slice(0,10)}`)).data,enabled:!!id});
 const attendees=useQuery<{confirmed:Attendee[];waitlist:Attendee[]}>({queryKey:['coach-attendees',id,selected?.id],queryFn:async()=> (await api.get(`/instructors/${id}/classes/${selected!.id}/attendees`)).data,enabled:!!id&&!!selected,refetchInterval:15000});
 const checkin=useMutation({mutationFn:async(bookingId:string)=>api.post(`/instructors/${id}/classes/${selected!.id}/checkin`,{bookingIds:[bookingId]}),onSuccess:async()=>{setError('');await cache.invalidateQueries({queryKey:['coach-attendees']});},onError:e=>setError(getErrorMessage(e))});
 return <main className="min-h-screen bg-altitud-cream px-5 py-6 text-altitud-charcoal"><div className="mx-auto max-w-5xl"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-altitud-sand pb-5"><Link to="/coach" className="text-xl font-heading">2707 ALTITUD · COACH</Link><button className="min-h-11 underline" onClick={()=>logout()}>Cerrar sesión</button></header><h1 className="mt-8 text-3xl font-heading">Tu semana, {user?.display_name}.</h1><p className="mt-2 text-muted-foreground">Solo tus sesiones asignadas. Horario del studio · Ciudad de México.</p>
 {!id&&<p role="alert" className="mt-6">Tu cuenta no tiene un perfil de coach vinculado. Contacta al studio.</p>}
 {sessions.isLoading&&id&&<p role="status" className="mt-6">Consultando tus sesiones…</p>}
 {sessions.isError&&<p role="alert" className="mt-6">No pudimos cargar tus sesiones. <button onClick={()=>sessions.refetch()}>Reintentar</button></p>}
 <div className="mt-8 grid gap-6 md:grid-cols-2"><section aria-label="Mis sesiones asignadas" className="space-y-3">{sessions.data?.map(c=><button key={c.id} onClick={()=>{setSelected(c);setError('');}} aria-pressed={selected?.id===c.id} className="w-full rounded-xl border border-altitud-sand p-4 text-left focus-visible:outline"><strong className="block text-xl">{c.class_type_name}</strong><span className="mt-1 block">{c.date.slice(0,10)} · {c.start_time.slice(0,5)}</span><span className="mt-1 block text-sm">{c.current_bookings}/{c.max_capacity} lugares · Ver asistentes</span></button>)}{sessions.data?.length===0&&<p>No tienes sesiones asignadas para esta semana.</p>}</section>
 <section aria-label="Asistentes" className="rounded-xl border border-altitud-sand p-5">{selected?<><h2 className="text-2xl font-heading">{selected.class_type_name}</h2><p>{selected.date.slice(0,10)} · {selected.start_time.slice(0,5)}</p>{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}{attendees.isLoading&&<p role="status">Consultando asistentes…</p>}{attendees.isError&&<p role="alert">No pudimos cargar asistentes. <button onClick={()=>attendees.refetch()}>Reintentar</button></p>}<ul className="mt-4 divide-y">{attendees.data?.confirmed.map(person=><li className="py-4" key={person.booking_id}><h3 className="font-semibold">{person.display_name}</h3>{person.alert_flag&&<p className="mt-2 font-semibold text-amber-900">{person.alert_message||'Revisa las indicaciones del studio antes de la sesión.'}</p>}{person.instructor_notes&&<p className="mt-2 text-sm">{person.instructor_notes}</p>}<p className="mt-2">{person.status==='checked_in'?'Asistencia registrada':person.status==='confirmed'?'Reserva confirmada':person.status}</p>{person.status==='confirmed'&&<button className="mt-3 min-h-11 rounded-full bg-altitud-olive px-5 text-white" disabled={checkin.isPending} onClick={()=>checkin.mutate(person.booking_id)}>Registrar asistencia</button>}</li>)}</ul>{attendees.data?.confirmed.length===0&&<p className="mt-4">Aún no hay asistentes confirmados.</p>}{!!attendees.data?.waitlist.length&&<p className="mt-4">{attendees.data.waitlist.length} personas en lista de espera; todavía no tienen lugar confirmado.</p>}</>:<p>Selecciona una sesión para ver asistentes e indicaciones.</p>}</section></div></div></main>;
}
export default function CoachDashboard(){return <AuthGuard requiredRoles={['instructor']}><CoachContent/></AuthGuard>;}
