import {test as base,expect,type Page} from '@playwright/test';
import pg from 'pg';import {randomUUID} from 'node:crypto';import {createRequire} from 'node:module';
const requireBackend=createRequire(new URL('../../../backend/package.json',import.meta.url));
const bcrypt=requireBackend('bcryptjs');export const origin='http://127.0.0.1:3525';
const target=new URL(process.env.DATABASE_URL||'');if(target.hostname!=='127.0.0.1'||target.port!=='54355'||target.pathname!=='/altitud_2707')throw Error('Disposable Walkin DB only');
export class WalkinPage{constructor(readonly page:Page){}async login(email:string,password:string){await this.page.goto(origin+'/login?returnUrl=%2Fadmin%2Fbookings');await this.page.getByLabel('Correo electrónico').fill(email);await this.page.getByLabel('Contraseña',{exact:true}).fill(password);await this.page.getByRole('button',{name:'Entrar a mi cuenta'}).click();await expect(this.page.getByRole('heading',{name:'Llegadas de hoy'})).toBeVisible();}}
type Fixture={pool:pg.Pool;ids:Record<string,string>;emails:Record<string,string>;password:string;phone:string;name:string};
export const test=base.extend<{fixture:Fixture}>({fixture:async({},use)=>{const pool=new pg.Pool({connectionString:target.href});const ids=Object.fromEntries(['admin','reception','client','instructor'].map(k=>[k,randomUUID()]));const password='SyntheticWalkin123!',hash=await bcrypt.hash(password,4),emails:Record<string,string>={},name='QA UI Walkin '+ids.client.slice(0,8),phone='529'+String(BigInt('0x'+ids.client.replaceAll('-','').slice(0,10))%1000000000n).padStart(9,'0');
for(const role of Object.keys(ids)){emails[role]=ids[role]+'@example.invalid';await pool.query('INSERT INTO users(id,email,password_hash,phone,display_name,role) VALUES($1,$2,$3,$4,$5,$6)',[ids[role],emails[role],hash,role==='client'?phone:'529'+String(BigInt('0x'+ids[role].replaceAll('-','').slice(0,10))%1000000000n).padStart(9,'0'),role==='client'?name:'QA UI '+role,role]);}
try{await use({pool,ids,emails,password,phone,name});}finally{await pool.end();}// Preserve synthetic own-ID records for supervisor SQL evidence. No broad cleanup.
},context:async({browser},use)=>{const c=await browser.newContext({viewport:{width:390,height:844},locale:'es-MX',timezoneId:'America/Mexico_City',serviceWorkers:'block'});await c.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await use(c);await c.close();}});export{expect};
