import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import api, { getErrorMessage } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import type { InaugurationConfig } from '@/pages/Inauguration';
type Attendee={id:string;displayName:string;email:string;attendeeCount:number;exercisesRegularly:boolean;exerciseType:string;activitiesInterest:boolean};
export function InaugurationSettings(){
 const config=useQuery<InaugurationConfig&{stats:{registrations:number;attendees:number;activitiesInterested:number}}>({queryKey:['inauguration-admin'],queryFn:async()=>(await api.get('/inauguration/admin')).data});
 const attendees=useQuery<Attendee[]>({queryKey:['inauguration-attendees'],queryFn:async()=>(await api.get('/inauguration/admin/registrations')).data});
 const [date,setDate]=useState('');const [time,setTime]=useState('');const [end,setEnd]=useState('');const [location,setLocation]=useState('');const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 useEffect(()=>{if(config.data){setDate(config.data.date||'');setTime(config.data.startTime||'');setEnd(config.data.endTime||'');setLocation(config.data.location);setOpen(config.data.registrationOpen);}},[config.data]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');setError('');try{await api.patch('/inauguration/admin',{date:date||null,startTime:time||null,endTime:end||null,location,registrationOpen:open});await config.refetch();setMessage('Configuración de inauguración guardada.');}catch(e){setError(getErrorMessage(e));}finally{setBusy(false);}}
 return <section id="inauguration-settings" className="space-y-6 border-t pt-8"><header><h2 className="text-xl font-semibold">Evento de inauguración</h2><p className="mt-2 text-sm text-muted-foreground">Registro independiente de las clases gratis. La fecha y la hora en blanco se muestran como pendientes de confirmar.</p><Link to="/inauguracion" className="mt-2 inline-block underline">Ver registro público</Link></header>
 {config.isLoading?<p role="status">Consultando configuración…</p>:config.isError?<p role="alert">No pudimos cargar el evento. <button className="underline" onClick={()=>void config.refetch()}>Reintentar</button></p>:<form onSubmit={save} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="inaug-date">Fecha</Label><Input id="inaug-date" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div><Label htmlFor="inaug-time">Hora · Ciudad de México</Label><Input id="inaug-time" type="time" value={time} onChange={e=>setTime(e.target.value)}/></div><div><Label htmlFor="inaug-end">Termina · Ciudad de México</Label><Input id="inaug-end" type="time" value={end} onChange={e=>setEnd(e.target.value)}/></div></div><div><Label htmlFor="inaug-location">Lugar</Label><Input id="inaug-location" required maxLength={500} value={location} onChange={e=>setLocation(e.target.value)}/></div><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={open} onChange={e=>setOpen(e.target.checked)}/>Permitir registros al evento</label>{error&&<p role="alert" className="text-destructive">{error}</p>}{message&&<p role="status">{message}</p>}<Button disabled={busy} type="submit">{busy?'Guardando…':'Guardar evento'}</Button></form>}
 <div><h3 className="font-semibold">Asistentes registrados</h3>{config.data&&<p className="my-2 text-sm text-muted-foreground">{config.data.stats.registrations} registros · {config.data.stats.attendees} asistentes en total · {config.data.stats.activitiesInterested} registros con interés en actividades</p>}{attendees.isLoading?<p role="status">Consultando asistentes…</p>:attendees.isError?<p role="alert">No pudimos consultar los registros. <button className="underline" onClick={()=>void attendees.refetch()}>Reintentar</button></p>:!attendees.data?.length?<p className="text-sm text-muted-foreground">Aún no hay registros para la inauguración.</p>:<ul className="divide-y">{attendees.data.map(a=><li key={a.id} className="space-y-1 py-4"><p className="font-medium">{a.displayName} · {a.attendeeCount} personas</p><p className="break-all text-sm">{a.email}</p><p className="text-sm text-muted-foreground">Ejercicio: {a.exercisesRegularly?a.exerciseType:'No regularmente'} · Actividades: {a.activitiesInterest?'Sí':'No'}</p></li>)}</ul>}<Button className="mt-3" variant="outline" onClick={()=>{void attendees.refetch();void config.refetch();}}>Actualizar asistentes</Button></div>
 </section>;
}
