import { useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import api, { getErrorMessage } from '@/lib/api';
import { useAuth } from '@/hooks/useAuth';
import { SiteHeader, SiteFooter } from '@/components/altitud/SiteShell';
import { OPENING_IMAGES } from '@/components/altitud/OpeningClassesSection';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
export type InaugurationConfig={title:string;date:string|null;startTime:string|null;endTime:string|null;location:string;registrationOpen:boolean;imageUrl:string|null;schedulePending:boolean};
type Registration={attendeeCount:number;exercisesRegularly:boolean;exerciseType:string;activitiesInterest:boolean};
export default function Inauguration(){
 const {isAuthenticated,isLoading:authLoading}=useAuth();const qc=useQueryClient();
 const config=useQuery<InaugurationConfig>({queryKey:['inauguration'],queryFn:async()=>(await api.get('/inauguration')).data});
 const mine=useQuery<Registration|null>({queryKey:['inauguration-mine'],queryFn:async()=>(await api.get('/inauguration/registrations/me')).data,enabled:isAuthenticated});
 const [count,setCount]=useState('1');const [exercise,setExercise]=useState('');const [type,setType]=useState('');const [activities,setActivities]=useState('');const [busy,setBusy]=useState(false);const [saved,setSaved]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{if(mine.data){setCount(String(mine.data.attendeeCount));setExercise(String(mine.data.exercisesRegularly));setType(mine.data.exerciseType||'');setActivities(String(mine.data.activitiesInterest));}},[mine.data]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setSaved(false);try{await api.post('/inauguration/registrations',{attendeeCount:Number(count),exercisesRegularly:exercise==='true',exerciseType:exercise==='true'?type:'',activitiesInterest:activities==='true'});setSaved(true);await qc.invalidateQueries({queryKey:['inauguration-mine']});}catch(e){setError(getErrorMessage(e));}finally{setBusy(false);}}
 return <div className="alt-site"><SiteHeader/><main className="mx-auto max-w-6xl px-6 py-12 md:py-20"><Link to="/#apertura" className="text-sm underline underline-offset-4">Volver a las experiencias de apertura</Link><div className="mt-8 grid items-start gap-10 md:grid-cols-2 lg:gap-16"><img src={config.data?.imageUrl ? `https://api.2707altitud.com.mx${config.data.imageUrl}` : OPENING_IMAGES.inauguration} alt="Invitación a la inauguración de 2707 Altitud" width="853" height="1014" className="w-full rounded-xl"/><div><p className="alt-eyebrow">INAUGURACIÓN · 2707 ALTITUD</p><h1 className="my-5 text-4xl md:text-5xl">Celebremos<br/>el comienzo.</h1><p className="mb-6 text-lg text-muted-foreground">Ven con tu gente y forma parte de nuestra comunidad desde el primer día.</p>
 {config.isLoading?<p role="status">Consultando el evento…</p>:config.isError?<p role="alert">No pudimos consultar el evento. <button className="underline" onClick={()=>void config.refetch()}>Reintentar</button></p>:config.data&&<><div className="mb-8 space-y-2 border-y py-5"><p>{config.data.title}</p><p>{config.data.date?config.data.date.split('-').reverse().join('/'): 'Fecha por confirmar'}{config.data.startTime?` · ${config.data.startTime}${config.data.endTime ? ` a ${config.data.endTime}` : ''} h`: ' · Horario por confirmar'}</p><p className="text-sm text-muted-foreground">{config.data.location}</p>{config.data.schedulePending&&<p className="text-sm text-altitud-earth">Puedes registrar tu asistencia. Consulta aquí la fecha y hora cuando el studio las confirme.</p>}</div>
 {!config.data.registrationOpen?<p>El registro está cerrado por el momento.</p>:authLoading?<p role="status">Consultando tu cuenta…</p>:!isAuthenticated?<div className="space-y-4"><p>Inicia sesión o crea tu cuenta para registrar tu asistencia y poder actualizar tus respuestas.</p><Link className="alt-button alt-button-olive" to="/login?returnUrl=%2Finauguracion">Iniciar sesión para registrarme</Link><Link className="block underline" to="/register?returnUrl=%2Finauguracion">Crear mi cuenta</Link></div>:mine.isLoading?<p role="status">Consultando tu registro…</p>:mine.isError?<p role="alert">No pudimos consultar tu registro. <button className="underline" onClick={()=>void mine.refetch()}>Reintentar</button></p>:<form onSubmit={submit} className="space-y-7">
 {mine.data&&<p className="font-medium text-altitud-olive">Ya tienes un registro. Puedes actualizar tus respuestas.</p>}
 <div><Label htmlFor="attendees">1. ¿Cuántas personas asistirán, incluyéndote?</Label><Input id="attendees" type="number" min="1" max="20" required value={count} onChange={e=>setCount(e.target.value)} className="mt-2 max-w-32"/><p className="mt-2 text-sm text-muted-foreground">Si vienes con una persona, selecciona 2.</p></div>
 <fieldset><legend className="text-sm font-medium">2. ¿Haces ejercicio regularmente?</legend><div className="mt-3 flex gap-6">{[['true','Sí'],['false','No']].map(([value,label])=><label key={value} className="flex min-h-11 items-center gap-2"><input type="radio" name="exercise" value={value} checked={exercise===value} onChange={()=>setExercise(value)} required/>{label}</label>)}</div>{exercise==='true'&&<div className="mt-3"><Label htmlFor="exercise-type">¿Qué tipo de ejercicio?</Label><Input id="exercise-type" className="mt-2" value={type} onChange={e=>setType(e.target.value)} maxLength={500} required placeholder="Por ejemplo: fuerza, running, pilates…"/></div>}</fieldset>
 <fieldset><legend className="text-sm font-medium">3. ¿Te gustaría participar en actividades y concursos?</legend><div className="mt-3 flex gap-6">{[['true','Sí'],['false','No']].map(([value,label])=><label key={value} className="flex min-h-11 items-center gap-2"><input type="radio" name="activities" value={value} checked={activities===value} onChange={()=>setActivities(value)} required/>{label}</label>)}</div></fieldset>
 <p className="text-sm text-muted-foreground">Este registro es para el evento. Las clases gratis se reservan por separado. Usaremos tus respuestas para organizar la asistencia y las actividades. <Link to="/privacy" className="underline">Aviso de privacidad</Link>.</p>
 {error&&<p role="alert" className="text-destructive">{error}</p>}{saved&&<p role="status" className="font-medium text-altitud-olive">Tu asistencia quedó registrada. ¡Nos vemos en Altitud!</p>}<Button type="submit" disabled={busy}>{busy?'Guardando…':mine.data?'Actualizar mi registro':'Confirmar mi asistencia'}</Button>
 </form>}</>}
 </div></div></main><SiteFooter/></div>;
}
