import { useState } from 'react';
import { Link } from 'react-router-dom';
import { SiteHeader, SiteFooter, Arrow } from '@/components/altitud/SiteShell';
import { StudioHours, StudioContact } from '@/components/altitud/StudioDetails';
import { STUDIO_SERVICES, FOUNDING_50, formatMxn } from '@/lib/studio';

const disciplines = [
  { ...STUDIO_SERVICES[0], number: '01', image: 'hybrid-training.jpg', imageAlt: 'Trabajo de fuerza y resistencia con trineo', note: 'Entrena para ir más lejos' },
  { ...STUDIO_SERVICES[1], number: '02', image: 'performance-disciplines.jpg', imageAlt: 'Trabajo de fuerza con mancuernas y entrenamiento en el studio', note: 'Una base fuerte lo cambia todo' },
];
const questions = [
  ['¿Puedo entrenar si estoy empezando?', 'Sí. Aquí tu punto de partida es tuyo. El coaching cercano nos permite adaptar el trabajo a tu nivel, cuidar tu técnica y acompañarte para construir una base sólida.'],
  ['¿Qué significa entrenamiento híbrido?', 'Combinamos trabajo de fuerza y resistencia cardiovascular. Es una forma de desarrollar una condición física completa y prepararte para distintos retos deportivos.'],
  ['¿Necesito experiencia en HYROX?', 'No necesitas haber competido. El entrenamiento híbrido es para quienes quieren comenzar y para atletas que buscan complementar su preparación para retos como HYROX.'],
  ['¿Puedo cancelar o cambiar mi clase?', 'Sí, con mínimo 4 horas de anticipación. Si cancelas después de ese plazo o no asistes, la clase se considera utilizada y no puede recuperarse.'],
  ['¿Cuánto tiempo tengo para usar mi paquete?', 'Los paquetes de 4, 8 y 12 clases y Unlimited tienen vigencia de 30 días. Las clases no utilizadas no son acumulables ni transferibles, salvo excepción autorizada por Altitud. Para las opciones de primera vez y clase suelta, consulta la vigencia con el studio.'],
  ['¿Qué llevo a mi primera clase?', 'Ropa deportiva cómoda, tenis para entrenar, agua y una toalla. Ven con disposición de aprender; el resto lo construimos juntos.'],
  ['¿Cómo reservo mi lugar?', 'Selecciona Reservar clase e inicia sesión o crea tu cuenta. Después elige una sesión disponible y confirma tu lugar desde tu app con un paquete o membresía activo. Entrenamos en grupos de hasta 12 personas.'],
];
export default function Index() {
  const [openQuestion, setOpenQuestion] = useState<number | null>(0);
  return <div className="alt-site alt-home"><a href="#contenido" className="alt-skip">Ir al contenido</a><SiteHeader /><main id="contenido">
    <section className="alt-hero">
      <div className="alt-hero-copy"><div className="alt-eyebrow"><span className="alt-status-dot" /> PERFORMANCE LIFESTYLE · ZINACANTEPEC</div><h1>Tu siguiente<br />nivel empieza<br /><span>aquí.</span></h1><p>Híbrido y funcional, fuerza y running. Grupos de hasta 12 personas para dar más de ti y sentirte parte.</p><div className="alt-hero-buttons"><Link className="alt-button alt-button-olive" to="/reservar">Encuentra tu clase <Arrow /></Link><a className="alt-text-link" href="#studio">Conoce Altitud <span aria-hidden="true">↓</span></a></div><div className="alt-hero-bottom"><span>Inspirados en la altitud.</span><span>ZINACANTEPEC, MÉXICO<br />2707 M S. N. M.</span></div></div>
      <div className="alt-hero-visual"><img src="/brand/hybrid-training.jpg" alt="Entrenamiento híbrido con empuje de trineo" width="1920" height="1080" /><div className="alt-image-top"><span>EL PROGRESO SE ENTRENA.</span><span>01 / EN MOVIMIENTO</span></div><div className="alt-image-bottom"><span><small>FUERZA. RESISTENCIA. COMUNIDAD.</small>Entrena con intención.</span><a href="#entrenamientos" aria-label="Descubre los entrenamientos" className="alt-circle-link"><Arrow /></a></div></div>
    </section>
    <div className="alt-values-strip"><span>ALTITUD</span><span aria-hidden="true">↗</span><span>DISCIPLINA</span><span aria-hidden="true">↗</span><span>COMUNIDAD</span><span aria-hidden="true">↗</span><span>EVOLUCIÓN</span><span aria-hidden="true">↗</span></div>
    <section className="alt-section alt-intro" id="studio"><div className="alt-eyebrow">01 / NUESTRA ESENCIA</div><div><h2>Un lugar para entrenar.<br /><span>Una comunidad para<br className="alt-desktop-break" /> llegar más lejos.</span></h2><div className="alt-intro-bottom"><p>Nacimos en Zinacantepec, a 2707 metros sobre el nivel del mar. Inspirados en el Nevado de Toluca, hacemos de cada entrenamiento una oportunidad para evolucionar.</p><p>Entrenamiento de alto nivel, atención cercana y un espacio donde cabes tal como eres. Aquí el progreso es personal. La energía es de todos.</p></div></div></section>
    <section className="alt-section alt-training" id="entrenamientos"><div className="alt-section-heading"><div><div className="alt-eyebrow">02 / ENCUENTRA TU MOVIMIENTO</div><h2>Encuentra tu ritmo.<br />Construye tu fuerza.</h2></div><p>Más fuerza. Más resistencia. Más tú.<br />Elige cómo quieres empezar.</p></div><div className="alt-discipline-grid">{disciplines.map(d => <article className="alt-discipline" key={d.id}><div className="alt-discipline-image"><img src={`/brand/${d.image}`} alt={d.imageAlt} loading="lazy" width="1920" height="1080" /><div className="alt-discipline-overline"><span>{d.number} / {d.label}</span><span>PARA TODOS LOS NIVELES</span></div><h3>{d.name}</h3></div><div className="alt-discipline-info"><div><p>{d.description}</p><span>{d.note}</span></div><Link className="alt-circle-link alt-circle-dark" to={`/reservar?tipo=${encodeURIComponent(d.name)}`} aria-label={`Ver clases de ${d.name.toLowerCase()}`}><Arrow /></Link></div></article>)}</div><article className="alt-running-feature"><div className="alt-running-photo"><img src="/brand/performance-disciplines.jpg" alt="Corredora en movimiento durante su entrenamiento" loading="lazy" width="1920" height="1080" /></div><div><div className="alt-eyebrow">03 / {STUDIO_SERVICES[2].label}</div><h3>{STUDIO_SERVICES[2].name}</h3><p>{STUDIO_SERVICES[2].description}</p><Link to="/reservar?tipo=Running" className="alt-text-link">Ver sesiones de running <Arrow /></Link></div></article><div className="alt-hyrox"><span className="alt-eyebrow">¿TIENES UN NUEVO RETO?</span><p>De tu primera sesión a tu próxima carrera.<br /><strong>Construye tu base para el entrenamiento híbrido y HYROX.</strong></p><Link to="/reservar" className="alt-text-link">Vamos por más <Arrow /></Link></div></section>
    <section className="alt-community"><div className="alt-community-image"><img src="/brand/community-training.jpg" alt="Atleta entrenando con cuerdas de batalla" loading="lazy" width="1920" height="1080" /></div><div className="alt-community-copy"><div className="alt-eyebrow">03 / EL PODER DE ENTRENAR JUNTOS</div><h2>El esfuerzo es tuyo.<br /><span>El impulso,<br />de todos.</span></h2><p>Más que un lugar donde entrenas. Una comunidad a la que quieres pertenecer.</p><ul><li><span>01</span>Hasta 12 personas, atención real.</li><li><span>02</span>Coaching que conoce tu proceso.</li><li><span>03</span>Energía que se contagia.</li></ul><Link className="alt-button alt-button-cream" to="/reservar">Encuentra tu lugar <Arrow /></Link></div></section>
    <StudioHours />
    <section className="alt-section alt-memberships" id="membresias"><div><div className="alt-eyebrow">04 / HAZLO PARTE DE TU VIDA</div><h2>Haz espacio<br />para tu<br /><span>mejor versión.</span></h2><p>Entrenar una vez es empezar.<br />Volver es lo que te transforma.</p></div><div className="alt-membership-options"><article><div><span className="alt-eyebrow">EL PRIMER PASO</span><h3>Conoce la experiencia</h3><p>Clase prueba por $100 MXN o 5 clases por $500 MXN para tu primera vez.</p><span className="alt-home-plan-price">Desde $100 <small>MXN</small></span></div><Link to="/pricing" aria-label="Ver opciones de primera vez"><Arrow /></Link></article><article><div><span className="alt-eyebrow">CONSTRUYE TU RUTINA</span><h3>Constancia a tu medida</h3><p>Paquetes de 4, 8 o 12 clases y Unlimited. Todos con vigencia de 30 días.</p><span className="alt-home-plan-price">Desde $649 <small>MXN</small></span></div><Link to="/pricing" aria-label="Ver precios de paquetes y membresías"><Arrow /></Link></article><article><div><span className="alt-eyebrow">PROMOCIÓN DE LANZAMIENTO</span><h3>Founding 50</h3><p>Unlimited con precio congelado durante 6 meses. Para las primeras 50 personas que adquieran la membresía y mantengan sus pagos consecutivos.</p><span className="alt-home-plan-price">{formatMxn(FOUNDING_50.price)} <small>MXN / mes</small></span></div><Link to="/pricing#founding-50" aria-label="Ver beneficios y condiciones de Founding 50"><Arrow /></Link></article><Link className="alt-text-link alt-pricing-link" to="/pricing">Comparar todas las opciones <Arrow /></Link></div></section>
    <section className="alt-section alt-faq" id="preguntas"><div><div className="alt-eyebrow">ANTES DE EMPEZAR</div><h2>Llega con ganas.<br />Y sin dudas.</h2><p>Tu primera clase, con confianza.</p></div><div>{questions.map(([q,a],i)=><div className="alt-faq-item" key={q}><h3><button aria-expanded={openQuestion===i} aria-controls={`answer-${i}`} onClick={()=>setOpenQuestion(openQuestion===i?null:i)}>{q}<span aria-hidden="true">{openQuestion===i?'−':'+'}</span></button></h3><div id={`answer-${i}`} hidden={openQuestion!==i}><p>{a}</p></div></div>)}</div></section>
    <StudioContact />
    <section className="alt-final-cta"><div className="alt-eyebrow">EL PRIMER PASO TAMBIÉN CUENTA.</div><div><h2>Nos vemos<br />en Altitud.</h2><Link className="alt-button alt-button-dark" to="/reservar">Vamos a entrenar <Arrow /></Link></div><span className="alt-cta-coordinate">ZINACANTEPEC, MÉXICO · 2707 M S. N. M.</span></section>
  </main><SiteFooter /></div>;
}
