import React from 'react';
import {render,screen,cleanup,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {Founding50Content} from '@/pages/admin/memberships/Founding50';
import api from '@/lib/api';
import {postFinancialOperation} from '@/lib/financial-intent';
jest.mock('@/lib/api',()=>({__esModule:true,default:{get:jest.fn(),post:jest.fn()},getStoredToken:()=>null,getErrorMessage:(e:any)=>e.message}));
jest.mock('@/lib/financial-intent',()=>({postFinancialOperation:jest.fn()}));
const member={can_renew:true,requires_policy_confirmation:false,renewal_block_reason:null,effective_benefit_mode:null,id:'enrollment',user_id:'client-1',display_name:'Marina QA',member_number:1,current_cycle:1,effective_status:'active',activated_on:'2026-09-20',paid_through:'2026-10-19',benefit_ends_on:'2027-03-20'};
function mount(){const q=new QueryClient({defaultOptions:{queries:{retry:false,gcTime:0},mutations:{retry:false}}});return render(<QueryClientProvider client={q}><Founding50Content/></QueryClientProvider>);}
beforeEach(()=>jest.clearAllMocks());afterEach(cleanup);
it('shows recoverable failed query rather than invented availability',async()=>{(api.get as jest.Mock).mockRejectedValue(new Error('No disponible'));mount();await screen.findByRole('alert');expect(screen.getByRole('button',{name:'Volver a consultar'})).toBeEnabled();expect(screen.queryByText(/50 lugares disponibles/)).toBeNull();});
it('explains an empty campaign and only paid registrations acquire a place',async()=>{(api.get as jest.Mock).mockResolvedValue({data:{members:[],acquired:0,capacity:50}});mount();await screen.findByText('Todavía no hay pagos Founding registrados.');expect(screen.getByText(/El primer pago validado asegura/)).toBeVisible();});
it('blocks a new first payment after the fiftieth place without blocking viewing history',async()=>{(api.get as jest.Mock).mockResolvedValue({data:{members:[member],acquired:50,capacity:50}});mount();await screen.findByText('Marina QA');expect(screen.getByRole('button',{name:'Registrar primer pago'})).toBeDisabled();expect(screen.getByRole('button',{name:'Registrar renovación de Marina QA'})).toBeEnabled();});
it('preserves selection when server rejects a renewal and sends fixed amount plus expected cycle',async()=>{(api.get as jest.Mock).mockResolvedValue({data:{members:[member],acquired:1,capacity:50}});(postFinancialOperation as jest.Mock).mockRejectedValue(new Error('El ciclo cambió; actualiza el historial'));mount();await userEvent.click(await screen.findByRole('button',{name:'Registrar renovación de Marina QA'}));await userEvent.click(screen.getByRole('button',{name:'Registrar pago recibido'}));await screen.findByText('El ciclo cambió; actualiza el historial');expect(postFinancialOperation).toHaveBeenCalledWith('/founding50/payments',expect.objectContaining({userId:'client-1',amount:1299,expectedCycle:1,paymentMethod:'cash'}));expect(screen.getByRole('button',{name:'Registrar pago recibido'})).toBeEnabled();});
it('never offers an unconfirmed seventh charge after the sixth paid cycle',async()=>{(api.get as jest.Mock).mockResolvedValue({data:{members:[{...member,current_cycle:6,can_renew:false,requires_policy_confirmation:true,renewal_block_reason:'La siguiente renovación requiere revisión'}],acquired:1,capacity:50}});mount();await screen.findByText('Marina QA');expect(screen.queryByRole('button',{name:'Registrar renovación de Marina QA'})).toBeNull();expect(screen.getByText(/La siguiente renovación requiere revisión/)).toBeVisible();});
it('requires a validated private proof for transfer before registering payment',async()=>{(api.get as jest.Mock).mockResolvedValue({data:{members:[member],acquired:1,capacity:50}});mount();await userEvent.click(await screen.findByRole('button',{name:'Registrar renovación de Marina QA'}));await userEvent.selectOptions(screen.getByLabelText('Método de pago'),'transfer');await userEvent.type(screen.getByLabelText('Folio del pago'),'QA-123');expect(screen.getByRole('button',{name:'Registrar pago recibido'})).toBeDisabled();expect(screen.getByLabelText('Comprobante de transferencia')).toBeVisible();});

it('shows the renewal authorized by the backend after six cycles under a calendar-month snapshot',async()=>{(api.get as jest.Mock).mockResolvedValue({data:{members:[{...member,current_cycle:6,effective_benefit_mode:'six_calendar_months',can_renew:true}],acquired:1,capacity:50}});mount();await screen.findByText('Marina QA');expect(screen.getByRole('button',{name:'Registrar renovación de Marina QA'})).toBeEnabled();});
it('honors a backend renewal block even before the sixth cycle',async()=>{(api.get as jest.Mock).mockResolvedValue({data:{members:[{...member,current_cycle:2,can_renew:false,renewal_block_reason:'El siguiente periodo ya está pagado'}],acquired:1,capacity:50}});mount();await screen.findByText('Marina QA');expect(screen.queryByRole('button',{name:'Registrar renovación de Marina QA'})).toBeNull();expect(screen.getByText('El siguiente periodo ya está pagado')).toBeVisible();});
