import React from 'react';import{render,screen,cleanup}from'@testing-library/react';import userEvent from'@testing-library/user-event';import{SeriesChangePanel}from'@/pages/admin/schedules/SeriesChangePanel';import api from'@/lib/api';
jest.mock('@/lib/api',()=>({__esModule:true,default:{post:jest.fn()},getErrorMessage:(e:any)=>e.message}));
const preview={applicable:[{id:'ok',date:'2036-01-14'}],blocked:[{id:'old',date:'2001-01-01',reason:'past_or_before_scope'},{id:'booked',date:'2036-01-21',reason:'booking_history'}],fingerprint:'fresh-proof',effectiveFrom:'2036-01-07',templateWillChange:true,warning:'Las clases con historial conservan su horario.'};
beforeEach(()=>jest.clearAllMocks());afterEach(cleanup);
it('requires scope preview before showing apply',async()=>{render(<SeriesChangePanel classId="class" changes={{startTime:'08:00'}} onApplied={jest.fn()}/>);expect(screen.queryByRole('button',{name:'Aplicar cambio revisado'})).toBeNull();expect(screen.getByLabelText('Aplicar a')).toHaveValue('one');});
it('shows protected classes and sends the reviewed fingerprint',async()=>{(api.post as jest.Mock).mockResolvedValue({data:preview});const done=jest.fn();render(<SeriesChangePanel classId="class" changes={{startTime:'08:00'}} onApplied={done}/>);await userEvent.selectOptions(screen.getByLabelText('Aplicar a'),'following');await userEvent.click(screen.getByRole('button',{name:'Revisar impacto'}));await screen.findByText('1 clases se actualizarán.');await userEvent.click(screen.getByText('Ver clases que conservan su horario'));expect(screen.getByText(/Tiene historial de reservas/)).toBeVisible();await userEvent.click(screen.getByRole('button',{name:'Aplicar cambio revisado'}));expect(api.post).toHaveBeenLastCalledWith('/classes/class/series-apply',{scope:'following',changes:{startTime:'08:00'},fingerprint:'fresh-proof'});expect(done).toHaveBeenCalled();});
it('changing scope invalidates prior confirmation',async()=>{(api.post as jest.Mock).mockResolvedValue({data:preview});render(<SeriesChangePanel classId="class" changes={{startTime:'08:00'}} onApplied={jest.fn()}/>);await userEvent.click(screen.getByRole('button',{name:'Revisar impacto'}));await screen.findByRole('button',{name:'Aplicar cambio revisado'});await userEvent.selectOptions(screen.getByLabelText('Aplicar a'),'all');expect(screen.queryByRole('button',{name:'Aplicar cambio revisado'})).toBeNull();});
it('stale server rejection requires a new preview rather than repeated blind apply',async()=>{(api.post as jest.Mock).mockResolvedValueOnce({data:preview}).mockRejectedValueOnce(new Error('La vista previa cambió'));render(<SeriesChangePanel classId="class" changes={{startTime:'08:00'}} onApplied={jest.fn()}/>);await userEvent.click(screen.getByRole('button',{name:'Revisar impacto'}));await userEvent.click(await screen.findByRole('button',{name:'Aplicar cambio revisado'}));await screen.findByRole('alert');expect(screen.queryByRole('button',{name:'Aplicar cambio revisado'})).toBeNull();});
it('blocked individual cannot be applied',async()=>{(api.post as jest.Mock).mockResolvedValue({data:{...preview,applicable:[]}});render(<SeriesChangePanel classId="class" changes={{startTime:'08:00'}} onApplied={jest.fn()}/>);await userEvent.click(screen.getByRole('button',{name:'Revisar impacto'}));expect(await screen.findByRole('button',{name:'Aplicar cambio revisado'})).toBeDisabled();});
