import {useEffect,useState} from 'react';
import api,{getErrorMessage} from '@/lib/api';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
const reasons:Record<string,string>={past_or_before_scope:'Pasada o anterior al alcance',booking_history:'Tiene historial de reservas',individual_exception:'Excepción individual',not_scheduled:'Ya iniciada, finalizada o cancelada'};
type Changes={startTime?:string;endTime?:string;maxCapacity?:number;instructorId?:string;classTypeId?:string;facilityId?:string|null};
export function SeriesChangePanel({classId,scheduleId,changes,onApplied}:{classId?:string;scheduleId?:string;changes:Changes;onApplied:()=>void}){
 const [scope,setScope]=useState(classId?'one':'all'),[effectiveFrom,setEffectiveFrom]=useState(''),[impact,setImpact]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const key=JSON.stringify(changes);useEffect(()=>{setImpact(null);setError('');},[key,scope,effectiveFrom,classId,scheduleId]);
 const body={scope,changes,...(!classId&&scope==='following'?{effectiveFrom}:{} )};const path=classId?`/classes/${classId}`:`/schedules/${scheduleId}`;
 async function run(apply=false){setBusy(true);setError('');try{const{data}=await api.post(path+(apply?'/series-apply':'/series-preview'),{...body,...(apply?{fingerprint:impact.fingerprint}:{})});if(apply)onApplied();else setImpact(data);}catch(e){setError(getErrorMessage(e));if(apply)setImpact(null);}finally{setBusy(false);}}
 return <section className="space-y-4 rounded-xl border p-4" aria-label="Alcance de la serie"><label className="grid gap-2 text-sm">Aplicar a<select className="min-h-11 rounded-md border bg-background px-3 text-base" value={scope} onChange={e=>setScope(e.target.value)} disabled={busy}>{classId&&<option value="one">Solo esta clase</option>}<option value="following">{classId?'Esta y las siguientes':'Desde una fecha'}</option><option value="all">Toda la serie futura</option></select></label>{!classId&&scope==='following'&&<label className="grid gap-2 text-sm">Desde la fecha<Input type="date" value={effectiveFrom} onChange={e=>setEffectiveFrom(e.target.value)}/></label>}<p className="text-sm text-muted-foreground">Las clases pasadas y las que tienen historial conservan su horario. Una edición individual se guarda como excepción.</p><Button type="button" variant="outline" disabled={busy||(!classId&&scope==='following'&&!effectiveFrom)} onClick={()=>void run()}>Revisar impacto</Button>
 {impact&&<div className="space-y-3" role="status"><p><strong>{impact.applicable.length} {impact.applicable.length===1?'clase se actualizará.':'clases se actualizarán.'}</strong> {impact.blocked.length} {impact.blocked.length===1?'conserva':'conservan'} su estado.</p>{impact.templateWillChange&&<p className="text-sm">Las nuevas clases de esta serie seguirán el cambio desde {impact.effectiveFrom}.</p>}{impact.blocked.length>0&&<details><summary className="cursor-pointer text-sm">Ver clases que conservan su horario</summary><ul className="mt-2 max-h-48 overflow-auto text-sm">{impact.blocked.map((item:any)=><li className="border-b py-2" key={item.id}>{item.date} · {reasons[item.reason]||item.reason}</li>)}</ul></details>}<p className="text-sm text-muted-foreground">{impact.warning}</p><Button type="button" disabled={busy||(scope==='one'&&!impact.applicable.length)} onClick={()=>void run(true)}>Aplicar cambio revisado</Button></div>}{busy&&<p role="status">Revisando la serie…</p>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}</section>;
}
export function SeriesTemplateEditor({schedule,onApplied}:{schedule:any;onApplied:()=>void}){const[start,setStart]=useState(schedule.start_time.slice(0,5)),[end,setEnd]=useState(schedule.end_time.slice(0,5)),[capacity,setCapacity]=useState(schedule.max_capacity);return <div className="space-y-4"><div className="grid grid-cols-2 gap-3"><label className="grid gap-2 text-sm">Inicio<Input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="grid gap-2 text-sm">Fin<Input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><label className="grid gap-2 text-sm">Capacidad<Input type="number" min="1" value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label><SeriesChangePanel scheduleId={schedule.id} changes={{startTime:start,endTime:end,maxCapacity:capacity}} onApplied={onApplied}/></div>;}
